window.APP_CONFIG = {
  API_BASE: "http://127.0.0.1:8000",
  APPS_SCRIPT_URL: "YOUR_LOCAL_OR_TEST_APPS_SCRIPT_URL",
  CLOUDINARY_CLOUD_NAME: "YOUR_CLOUD_NAME",
  CLOUDINARY_UPLOAD_PRESET: "YOUR_UNSIGNED_PRESET",
  AUTH_STORAGE_KEY: "gacha_app_auth_v1",
  RESULT_STORAGE_KEY: "gacha_last_result",
  POST_SUCCESS_NOTICE_KEY: "gacha_post_success_notice"
};
